In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import os

In [2]:
path_x = 'landmarks.csv'
path_y = 'labels.csv'
df_x = pd.read_csv(path_x)
df_y = pd.read_csv(path_y)


df_x.drop(columns=["pose_id"], inplace=True)
df_y.drop(columns=["pose_id"], inplace=True)

In [12]:
df_index = df_x.head(2)
# df_index

### Save to csv
import os  
os.makedirs('Data_CSV', exist_ok=True)  
df_index.to_csv('Data_CSV/dataframes_demo.csv', index=False)

In [9]:
df_x.head(10)
df_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 99 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   x_nose              1372 non-null   float64
 1   y_nose              1372 non-null   float64
 2   z_nose              1372 non-null   float64
 3   x_left_eye_inner    1372 non-null   float64
 4   y_left_eye_inner    1372 non-null   float64
 5   z_left_eye_inner    1372 non-null   float64
 6   x_left_eye          1372 non-null   float64
 7   y_left_eye          1372 non-null   float64
 8   z_left_eye          1372 non-null   float64
 9   x_left_eye_outer    1372 non-null   float64
 10  y_left_eye_outer    1372 non-null   float64
 11  z_left_eye_outer    1372 non-null   float64
 12  x_right_eye_inner   1372 non-null   float64
 13  y_right_eye_inner   1372 non-null   float64
 14  z_right_eye_inner   1372 non-null   float64
 15  x_right_eye         1372 non-null   float64
 16  y_right_eye         1372 non-null   float64
 17  z_right_eye         1372 non-null   float64
 18  x_right_eye_outer   1372 non-null   float64
 19  y_right_eye_outer   1372 non-null   float64
 20  z_right_eye_outer   1372 non-null   float64
 21  x_left_ear          1372 non-null   float64
 22  y_left_ear          1372 non-null   float64
 23  z_left_ear          1372 non-null   float64
 24  x_right_ear         1372 non-null   float64
 25  y_right_ear         1372 non-null   float64
 26  z_right_ear         1372 non-null   float64
 27  x_mouth_left        1372 non-null   float64
 28  y_mouth_left        1372 non-null   float64
 29  z_mouth_left        1372 non-null   float64
 30  x_mouth_right       1372 non-null   float64
 31  y_mouth_right       1372 non-null   float64
 32  z_mouth_right       1372 non-null   float64
 33  x_left_shoulder     1372 non-null   float64
 34  y_left_shoulder     1372 non-null   float64
 35  z_left_shoulder     1372 non-null   float64
 36  x_right_shoulder    1372 non-null   float64
 37  y_right_shoulder    1372 non-null   float64
 38  z_right_shoulder    1372 non-null   float64
 39  x_left_elbow        1372 non-null   float64
 40  y_left_elbow        1372 non-null   float64
 41  z_left_elbow        1372 non-null   float64
 42  x_right_elbow       1372 non-null   float64
 43  y_right_elbow       1372 non-null   float64
 44  z_right_elbow       1372 non-null   float64
 45  x_left_wrist        1372 non-null   float64
 46  y_left_wrist        1372 non-null   float64
 47  z_left_wrist        1372 non-null   float64
 48  x_right_wrist       1372 non-null   float64
 49  y_right_wrist       1372 non-null   float64
 50  z_right_wrist       1372 non-null   float64
 51  x_left_pinky_1      1372 non-null   float64
 52  y_left_pinky_1      1372 non-null   float64
 53  z_left_pinky_1      1372 non-null   float64
 54  x_right_pinky_1     1372 non-null   float64
 55  y_right_pinky_1     1372 non-null   float64
 56  z_right_pinky_1     1372 non-null   float64
 57  x_left_index_1      1372 non-null   float64
 58  y_left_index_1      1372 non-null   float64
 59  z_left_index_1      1372 non-null   float64
 60  x_right_index_1     1372 non-null   float64
 61  y_right_index_1     1372 non-null   float64
 62  z_right_index_1     1372 non-null   float64
 63  x_left_thumb_2      1372 non-null   float64
 64  y_left_thumb_2      1372 non-null   float64
 65  z_left_thumb_2      1372 non-null   float64
 66  x_right_thumb_2     1372 non-null   float64
 67  y_right_thumb_2     1372 non-null   float64
 68  z_right_thumb_2     1372 non-null   float64
 69  x_left_hip          1372 non-null   float64
 70  y_left_hip          1372 non-null   float64
 71  z_left_hip          1372 non-null   float64
 72  x_right_hip         1372 non-null   float64
 73  y_right_hip         1372 non-null   float64
 74  z_right_hip         1372 non-null   float64
 75  x_left_knee         1372 non-null   float64
 76  y_left_knee         1372 non-null   float64
 77  z_left_knee         1372 non-null   float64
 78  x_right_knee        1372 non-null   float64
 79  y_right_knee        1372 non-null   float64
 80  z_right_knee        1372 non-null   float64
 81  x_left_ankle        1372 non-null   float64
 82  y_left_ankle        1372 non-null   float64
 83  z_left_ankle        1372 non-null   float64
 84  x_right_ankle       1372 non-null   float64
 85  y_right_ankle       1372 non-null   float64
 86  z_right_ankle       1372 non-null   float64
 87  x_left_heel         1372 non-null   float64
 88  y_left_heel         1372 non-null   float64
 89  z_left_heel         1372 non-null   float64
 90  x_right_heel        1372 non-null   float64
 91  y_right_heel        1372 non-null   float64
 92  z_right_heel        1372 non-null   float64
 93  x_left_foot_index   1372 non-null   float64
 94  y_left_foot_index   1372 non-null   float64
 95  z_left_foot_index   1372 non-null   float64
 96  x_right_foot_index  1372 non-null   float64
 97  y_right_foot_index  1372 non-null   float64
 98  z_right_foot_index  1372 non-null   float64
dtypes: float64(99)
memory usage: 1.0 MB

In [10]:
df_y.head(10)
df_y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   pose    1372 non-null   object
dtypes: object(1)
memory usage: 10.8+ KB

In [11]:
### select two labels
df_y.head()

                 pose
0  jumping_jacks_down
1  jumping_jacks_down
2  jumping_jacks_down
3  jumping_jacks_down
4  jumping_jacks_down

In [12]:
df_y.pose.unique()
# df_y.info()

array(['jumping_jacks_down', 'jumping_jacks_up', 'pullups_down',
       'pullups_up', 'pushups_down', 'pushups_up', 'situp_down',
       'situp_up', 'squats_down', 'squats_up'], dtype=object)

In [13]:
df_x.loc[df_y.pose == 'pushups_up']

,x_nose,y_nose,z_nose,x_left_eye_inner,y_left_eye_inner,z_left_eye_inner,x_left_eye,y_left_eye,z_left_eye,x_left_eye_outer,...,z_left_heel,x_right_heel,y_right_heel,z_right_heel,x_left_foot_index,y_left_foot_index,z_left_foot_index,x_right_foot_index,y_right_foot_index,z_right_foot_index
761,11.185157,5.892762,-220.081240,12.562175,1.308306,-220.477170,13.732613,0.450217,-220.518020,14.875169,...,179.911350,-23.392162,46.674423,184.999220,13.174011,18.155848,163.078280,-23.444357,57.711105,165.341980
762,3.448390,-7.783039,-254.235210,6.426187,-15.067614,-255.776860,8.276227,-16.097488,-255.796480,10.009254,...,261.519930,-15.777005,5.429411,257.028900,3.947560,35.179882,238.987090,-21.231554,24.110815,235.118600
763,-52.969950,15.338495,-14.907137,-55.671480,12.805885,-21.459467,-55.698060,12.115666,-21.467750,-55.751030,...,-20.500261,59.197628,38.129860,57.980580,56.006477,67.882515,-37.468180,51.483590,61.572540,46.710632
764,-49.171170,-11.476644,-28.905163,-51.217205,-13.957122,-35.278355,-51.137115,-14.476606,-35.279440,-51.068783,...,-14.059955,53.792007,29.601288,56.783127,48.558200,54.931026,-32.618572,45.228710,48.748077,44.664845
765,13.569203,21.441511,-237.883590,15.189288,20.450985,-239.822770,16.475620,20.427360,-239.871100,17.525700,...,61.990536,-43.114480,70.085680,39.978474,-52.065490,85.376730,24.354063,-51.995647,83.393760,-3.862757
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900,-53.700085,-24.679771,-116.394760,-53.688630,-32.893566,-116.161330,-52.558350,-34.532578,-116.157530,-51.431286,...,78.111900,38.215560,13.383612,122.475780,44.484850,38.744633,68.894220,34.356680,30.923948,119.671480
901,40.282230,-32.185070,-109.254620,42.401726,-37.357334,-107.390760,42.825165,-37.765330,-107.420746,43.281250,...,124.953670,-41.053387,22.570484,99.924940,-31.191698,40.336315,120.683410,-42.020206,48.701153,88.933880
902,-5.475590,12.646519,-445.800080,-6.350753,7.781396,-458.567570,-5.198027,6.810925,-458.579440,-4.076397,...,483.923700,53.523148,55.513603,460.064760,60.325825,73.007706,467.302000,71.373180,70.041900,438.080700
903,-63.830894,-22.722176,-87.558280,-62.937565,-29.246395,-91.378080,-62.027230,-29.714737,-91.391230,-60.903250,...,72.126820,46.943180,9.129583,111.829605,46.480460,32.879654,61.751400,41.056590,28.391827,107.393480
904,-65.973076,10.455855,101.126100,-66.538180,16.318516,105.418720,-65.191660,17.730310,105.433044,-64.942210,...,-5.678543,44.063927,48.824448,-90.907960,40.884640,81.866630,-14.039267,56.082188,57.646370,-103.624110

In [14]:
df_x.loc[df_y.pose == 'pushups_down']

,x_nose,y_nose,z_nose,x_left_eye_inner,y_left_eye_inner,z_left_eye_inner,x_left_eye,y_left_eye,z_left_eye,x_left_eye_outer,...,z_left_heel,x_right_heel,y_right_heel,z_right_heel,x_left_foot_index,y_left_foot_index,z_left_foot_index,x_right_foot_index,y_right_foot_index,z_right_foot_index
659,3.200396,83.510440,-150.641980,5.292401,80.629990,-159.142930,6.740037,79.560450,-159.155690,8.174375,...,251.491930,-8.042053,-31.597647,256.985500,4.678776,-7.875343,267.167720,-8.543862,-7.613607,271.634550
660,3.611730,83.209755,-186.588930,4.724235,79.553830,-198.540530,5.818887,79.025696,-198.536450,8.913429,...,320.884830,-10.411005,-35.186325,325.971800,6.692365,-8.097569,338.320600,-10.695232,-10.641149,340.250120
661,-51.674007,6.761852,-6.694558,-53.535090,3.152715,-12.331046,-53.488003,2.495730,-12.339450,-53.457355,...,-0.652858,58.029568,-7.942425,46.844543,58.357136,18.271772,-14.846756,54.290043,14.974644,37.225820
662,7.565488,70.644170,-272.700000,11.533144,67.499855,-294.854860,12.979317,67.255310,-294.844700,14.475916,...,361.397060,-9.979975,-41.188705,371.955300,11.323601,-70.567130,368.911040,-10.243016,-36.966450,384.443760
663,-3.142754,-15.859342,-276.935120,-2.929307,-36.975080,-281.078500,0.235346,-38.858430,-281.076140,3.363623,...,275.694430,-35.235806,-31.433136,274.455800,-24.609259,-18.214708,269.081940,-36.913334,-23.614384,266.032780
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
756,-51.377890,48.213432,-64.634440,-52.969720,45.066853,-71.032070,-52.565544,44.486908,-71.020180,-52.139656,...,17.204000,45.645720,-16.515026,131.000090,67.093230,30.724789,-0.312525,44.178886,2.283015,131.151930
757,64.850930,35.622770,-145.201810,66.834670,26.845608,-145.413150,67.458220,24.203093,-145.427430,62.799335,...,155.073120,-3.018449,29.501347,130.545330,9.185700,33.111420,161.751830,7.810172,38.878296,135.986250
758,-54.677643,12.135875,-31.398750,-57.276750,9.978576,-38.935010,-57.215584,9.622678,-38.943684,-57.141180,...,22.426437,50.354810,-33.335320,119.995200,60.213356,-7.526650,8.655777,53.947020,-12.919101,114.615140
759,59.962470,-0.502117,0.065848,59.210957,-4.716687,4.692794,58.859360,-4.953800,4.688657,58.472040,...,31.859095,-73.145935,-5.021749,-25.253033,-63.272644,23.357150,18.110104,-66.960270,24.778774,-43.914665
760,53.416187,20.108335,-13.498150,55.559307,16.903566,-11.811872,55.578660,16.491152,-11.814120,55.589874,...,82.270810,-63.909554,1.729039,8.220594,-47.315544,14.252660,82.265530,-57.102196,26.584259,0.351292

In [15]:
df_y.loc[df_y.pose == 'pushups_up']

           pose
761  pushups_up
762  pushups_up
763  pushups_up
764  pushups_up
765  pushups_up
..          ...
900  pushups_up
901  pushups_up
902  pushups_up
903  pushups_up
904  pushups_up

[144 rows x 1 columns]

In [16]:
df_y.loc[df_y.pose == 'pushups_down']

             pose
659  pushups_down
660  pushups_down
661  pushups_down
662  pushups_down
663  pushups_down
..            ...
756  pushups_down
757  pushups_down
758  pushups_down
759  pushups_down
760  pushups_down

[102 rows x 1 columns]

In [17]:
data_pushups_up = df_x.loc[df_y.pose == 'pushups_up']
data_pushups_down = df_x.loc[df_y.pose == 'pushups_down']

label_pushups_up = df_y.loc[df_y.pose == 'pushups_up']
label_pushups_down = df_y.loc[df_y.pose == 'pushups_down']

In [18]:

X = pd.concat([data_pushups_up, data_pushups_down], ignore_index=True)
y = pd.concat([label_pushups_up, label_pushups_down], ignore_index=True)

y.replace("pushups_up", "1", inplace= True)
y.replace("pushups_down", "0", inplace= True)

In [19]:
X_input = X.to_numpy(dtype= np.float32)
y_input = y.to_numpy(dtype= np.uint8)

In [20]:
#### X + y -> Data frames
df = pd.concat([X, y], axis= 1)

In [21]:
### Save to csv
import os  
os.makedirs('Data_CSV', exist_ok=True)  
df.to_csv('Data_CSV/landmarks.csv', index=False)

## Code final

In [23]:
pose_A = 'pushups_up'
pose_B = 'pushups_down'

data_pushups_up = df_x.loc[df_y.pose == 'pushups_up']
data_pushups_down = df_x.loc[df_y.pose == 'pushups_down']

label_pushups_up = df_y.loc[df_y.pose == 'pushups_up']
label_pushups_down = df_y.loc[df_y.pose == 'pushups_down']

X = pd.concat([data_pushups_up, data_pushups_down], ignore_index=True)
y = pd.concat([label_pushups_up, label_pushups_down], ignore_index=True)

y.replace("pushups_up", "1", inplace= True)
y.replace("pushups_down", "0", inplace= True)

df = pd.concat([X, y], axis= 1)

### Save to csv
import os  
os.makedirs('Data_CSV', exist_ok=True)  
df.to_csv('Data_CSV/landmarks.csv', index=False)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 100 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   x_nose              246 non-null    float64
 1   y_nose              246 non-null    float64
 2   z_nose              246 non-null    float64
 3   x_left_eye_inner    246 non-null    float64
 4   y_left_eye_inner    246 non-null    float64
 5   z_left_eye_inner    246 non-null    float64
 6   x_left_eye          246 non-null    float64
 7   y_left_eye          246 non-null    float64
 8   z_left_eye          246 non-null    float64
 9   x_left_eye_outer    246 non-null    float64
 10  y_left_eye_outer    246 non-null    float64
 11  z_left_eye_outer    246 non-null    float64
 12  x_right_eye_inner   246 non-null    float64
 13  y_right_eye_inner   246 non-null    float64
 14  z_right_eye_inner   246 non-null    float64
 15  x_right_eye         246 non-null    float64
 16  y_right_eye         246 non-null    float64
 17  z_right_eye         246 non-null    float64
 18  x_right_eye_outer   246 non-null    float64
 19  y_right_eye_outer   246 non-null    float64
 20  z_right_eye_outer   246 non-null    float64
 21  x_left_ear          246 non-null    float64
 22  y_left_ear          246 non-null    float64
 23  z_left_ear          246 non-null    float64
 24  x_right_ear         246 non-null    float64
 25  y_right_ear         246 non-null    float64
 26  z_right_ear         246 non-null    float64
 27  x_mouth_left        246 non-null    float64
 28  y_mouth_left        246 non-null    float64
 29  z_mouth_left        246 non-null    float64
 30  x_mouth_right       246 non-null    float64
 31  y_mouth_right       246 non-null    float64
 32  z_mouth_right       246 non-null    float64
 33  x_left_shoulder     246 non-null    float64
 34  y_left_shoulder     246 non-null    float64
 35  z_left_shoulder     246 non-null    float64
 36  x_right_shoulder    246 non-null    float64
 37  y_right_shoulder    246 non-null    float64
 38  z_right_shoulder    246 non-null    float64
 39  x_left_elbow        246 non-null    float64
 40  y_left_elbow        246 non-null    float64
 41  z_left_elbow        246 non-null    float64
 42  x_right_elbow       246 non-null    float64
 43  y_right_elbow       246 non-null    float64
 44  z_right_elbow       246 non-null    float64
 45  x_left_wrist        246 non-null    float64
 46  y_left_wrist        246 non-null    float64
 47  z_left_wrist        246 non-null    float64
 48  x_right_wrist       246 non-null    float64
 49  y_right_wrist       246 non-null    float64
 50  z_right_wrist       246 non-null    float64
 51  x_left_pinky_1      246 non-null    float64
 52  y_left_pinky_1      246 non-null    float64
 53  z_left_pinky_1      246 non-null    float64
 54  x_right_pinky_1     246 non-null    float64
 55  y_right_pinky_1     246 non-null    float64
 56  z_right_pinky_1     246 non-null    float64
 57  x_left_index_1      246 non-null    float64
 58  y_left_index_1      246 non-null    float64
 59  z_left_index_1      246 non-null    float64
 60  x_right_index_1     246 non-null    float64
 61  y_right_index_1     246 non-null    float64
 62  z_right_index_1     246 non-null    float64
 63  x_left_thumb_2      246 non-null    float64
 64  y_left_thumb_2      246 non-null    float64
 65  z_left_thumb_2      246 non-null    float64
 66  x_right_thumb_2     246 non-null    float64
 67  y_right_thumb_2     246 non-null    float64
 68  z_right_thumb_2     246 non-null    float64
 69  x_left_hip          246 non-null    float64
 70  y_left_hip          246 non-null    float64
 71  z_left_hip          246 non-null    float64
 72  x_right_hip         246 non-null    float64
 73  y_right_hip         246 non-null    float64
 74  z_right_hip         246 non-null    float64
 75  x_left_knee         246 non-null    float64
 76  y_left_knee         246 non-null    float64
 77  z_left_knee         246 non-null    float64
 78  x_right_knee        246 non-null    float64
 79  y_right_knee        246 non-null    float64
 80  z_right_knee        246 non-null    float64
 81  x_left_ankle        246 non-null    float64
 82  y_left_ankle        246 non-null    float64
 83  z_left_ankle        246 non-null    float64
 84  x_right_ankle       246 non-null    float64
 85  y_right_ankle       246 non-null    float64
 86  z_right_ankle       246 non-null    float64
 87  x_left_heel         246 non-null    float64
 88  y_left_heel         246 non-null    float64
 89  z_left_heel         246 non-null    float64
 90  x_right_heel        246 non-null    float64
 91  y_right_heel        246 non-null    float64
 92  z_right_heel        246 non-null    float64
 93  x_left_foot_index   246 non-null    float64
 94  y_left_foot_index   246 non-null    float64
 95  z_left_foot_index   246 non-null    float64
 96  x_right_foot_index  246 non-null    float64
 97  y_right_foot_index  246 non-null    float64
 98  z_right_foot_index  246 non-null    float64
 99  pose                246 non-null    object
dtypes: float64(99), object(1)
memory usage: 192.3+ KB